### PR TITLE
Shortner 

### PR DESCRIPTION
**Pull request by rubandurai27**
Shortner Support

### CODE REVIEW

**Comment by Adarsh-Goel** [comment]
@rubandurai27 Pull rejected instead of just adding shortner you added your branding and some bloatware!.
Why should I accept it it has TN Botz branding everywhere!

**Comment by rubandurai27** [comment]
> @rubandurai27 Pull rejected instead of just adding shortner you added your branding and some bloatware!. Why should I accept it it has TN Botz branding everywhere!

That's for my personal use only . Scrap shorter code only

**Comment by rubandurai27** [comment]
> @rubandurai27 Pull rejected instead of just adding shortner you added your branding and some bloatware!. Why should I accept it it has TN Botz branding everywhere!

`https://github.com/rubandurai27/Filestreambot-pro/blob/afdd592385c380a8ac9edde36d79c2c9b9a155b6/Adarsh/bot/plugins/stream.py#L141` 

Add this line .

**Comment by rubandurai27** [comment]
> > @rubandurai27 Pull rejected instead of just adding shortner you added your branding and some bloatware!. Why should I accept it it has TN Botz branding everywhere!
> 
> `https://github.com/rubandurai27/Filestreambot-pro/blob/afdd592385c380a8ac9edde36d79c2c9b9a155b6/Adarsh/bot/plugins/stream.py#L141`
> 
> Add this line .

Screenshot_2022-09-12-17-05-59-937_org telegram plus
 
Code working correctly.  But bot giving long url 👆

**Comment by rubandurai27** [comment]
> Shortner Support

Screenshot_2022-09-12-17-05-59-937_org telegram plus

**Pull request closed without merging**
